export const res_details = [
  {
    id: "res_101",
    name: "La Pino'z Pizza",
    status: "OPEN",
    cuisines: ["Italian", "Pizza"],
    rating: 4.5,
    deliveryTime: "30-40 min",
    avgCost: 350,
    priceRange: "₹₹",
    image: "https://foodish-api.com/images/pizza/pizza63.jpg",
  },
  {
    id: "res_102",
    name: "Spice Route",
    status: "OPEN",
    cuisines: ["Indian", "North Indian"],
    rating: 4.2,
    deliveryTime: "25-35 min",
    avgCost: 300,
    priceRange: "₹₹",
    image: "https://foodish-api.com/images/pasta/pasta6.jpg",
  },
  {
    id: "res_103",
    name: "Dragon Bowl",
    status: "CLOSED",
    cuisines: ["Chinese", "Asian"],
    rating: 4.0,
    deliveryTime: "35-45 min",
    avgCost: 400,
    priceRange: "₹₹₹",
    image: "https://foodish-api.com/images/butter-chicken/butter-chicken2.jpg",
  },
  {
    id: "res_104",
    name: "Burger Hub",
    status: "OPEN",
    cuisines: ["Fast Food", "Burgers"],
    rating: 4.3,
    deliveryTime: "20-30 min",
    avgCost: 250,
    priceRange: "₹",
    image: "https://foodish-api.com/images/burger/burger4.jpg",
  },
  {
    id: "res_105",
    name: "Sweet Tooth",
    status: "CLOSED",
    cuisines: ["Desserts", "Bakery"],
    rating: 4.6,
    deliveryTime: "15-25 min",
    avgCost: 200,
    priceRange: "₹",
    image: "https://foodish-api.com/images/dessert/dessert1.jpg",
  },
];
