export const res_details = [
  {
    id: "res_101",
    name: "La Pino'z Pizza",
    status: "OPEN",
    cuisines: ["Italian", "Pizza"],
    rating: 4.5,
    deliveryTime: "30-40 min",
    avgCost: 350,
    priceRange: "₹₹",
    image: "https://foodish-api.com/images/pizza/pizza63.jpg",
  },
  {
    id: "res_102",
    name: "Spice Route",
    status: "OPEN",
    cuisines: ["Indian", "North Indian"],
    rating: 4.2,
    deliveryTime: "25-35 min",
    avgCost: 300,
    priceRange: "₹₹",
    image: "https://foodish-api.com/images/pasta/pasta6.jpg",
  },
  {
    id: "res_103",
    name: "Dragon Bowl",
    status: "CLOSED",
    cuisines: ["Chinese", "Asian"],
    rating: 4.0,
    deliveryTime: "35-45 min",
    avgCost: 400,
    priceRange: "₹₹₹",
    image: "https://foodish-api.com/images/butter-chicken/butter-chicken2.jpg",
  },
  {
    id: "res_104",
    name: "Burger Hub",
    status: "OPEN",
    cuisines: ["Fast Food", "Burgers"],
    rating: 4.3,
    deliveryTime: "20-30 min",
    avgCost: 250,
    priceRange: "₹",
    image: "https://foodish-api.com/images/burger/burger4.jpg",
  },
  {
    id: "res_105",
    name: "Sweet Tooth",
    status: "CLOSED",
    cuisines: ["Desserts", "Bakery"],
    rating: 4.6,
    deliveryTime: "15-25 min",
    avgCost: 200,
    priceRange: "₹",
    image: "https://foodish-api.com/images/dessert/dessert1.jpg",
  },
  {
    id: "res_110",
    name: "South Delight",
    status: "OPEN",
    cuisines: ["South Indian"],
    rating: 4.5,
    deliveryTime: "20-30 min",
    avgCost: 220,
    priceRange: "₹",
    image: "https://foodish-api.com/images/idly/idly16.jpg",
  },
  {
    id: "res_111",
    name: "Tandoori Flames",
    status: "OPEN",
    cuisines: ["Indian", "Mughlai"],
    rating: 4.0,
    deliveryTime: "40-50 min",
    avgCost: 450,
    priceRange: "₹₹₹",
    image: "https://foodish-api.com/images/butter-chicken/butter-chicken15.jpg",
  },
  {
    id: "res_112",
    name: "Cafe Mocha",
    status: "OPEN",
    cuisines: ["Cafe", "Beverages"],
    rating: 4.6,
    deliveryTime: "15-25 min",
    avgCost: 180,
    priceRange: "₹",
    image: "https://foodish-api.com/images/pasta/pasta5.jpg",
  },
  {
    id: "res_113",
    name: "Mexi Grill",
    status: "CLOSED",
    cuisines: ["Mexican"],
    rating: 4.1,
    deliveryTime: "30-40 min",
    avgCost: 380,
    priceRange: "₹₹",
    image: "https://foodish-api.com/images/butter-chicken/butter-chicken9.jpg",
  },
  {
    id: "res_114",
    name: "Healthy Bowl",
    status: "OPEN",
    cuisines: ["Healthy", "Salads"],
    rating: 4.7,
    deliveryTime: "20-30 min",
    avgCost: 300,
    priceRange: "₹₹",
    image: "https://foodish-api.com/images/dosa/dosa69.jpg",
  },
  {
    id: "res_115",
    name: "Midnight Biryani",
    status: "OPEN",
    cuisines: ["Biryani", "Indian"],
    rating: 4.4,
    deliveryTime: "35-45 min",
    avgCost: 320,
    priceRange: "₹₹",
    image: "https://foodish-api.com/images/biryani/biryani65.jpg",
  },
];
